### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by frederikaalund** [Frotty/ConflagrationSpell#1]
I'm new to Wurst so bear with me here.

I'm reading through the nice [beginners guide](https://wurstlang.org/tutorials/wurstbeginner.html) but noticed what I believe to be a typo in the [code](https://github.com/Frotty/ConflagrationSpell/blob/master/wurst/Conflagration.wurst#L30):

    buffMap.put(caster, cb)

Shouldn't this be:

    buffMap.put(u, cb)

Am I missing something here? Again, I haven't written a single line of Wurst yet, so I might very well be wrong. Thanks for the nice tutorial in any case.

**Comment by Frotty** [comment]
Oops, good catch 👍 
Right now the buff doesn't expire correctly.

Thanks for the report.
